import { join } from 'pathe';
import { promises } from 'node:fs';
import MagicString from 'magic-string';
import { BoxClient } from 'box-node-sdk';
import { pascalCase } from '@whoj/utils-core';
import { createFilter } from '@rollup/pluginutils';
import { useNuxt, addTemplate, resolvePath, addTypeTemplate, addServerImports, addImportsSources, addServerTemplate } from '@nuxt/kit';

import type { ModuleOptions } from '../types';

export function registerImports(resolve: (...p: string[]) => string, options: ModuleOptions, nuxt = useNuxt()) {
  const managerImports = createClientClass(options, nuxt);

  if (options.mode !== 'server') {
    const sources = [{
      from: resolve('./runtime/app/composables/auth'),
      imports: ['useBoxAuth']
    }, {
      from: resolve('./runtime/app/composables/client'),
      imports: ['useBoxClient', 'useBoxBasicClient', 'createBoxClient']
    }];

    if (options.managers?.composables !== false) {
      sources.push({
        from: '#nuxt/box-sdk/managers',
        imports: managerImports
      });
    }
    addImportsSources(sources);
  }

  if (options.mode !== 'client') {
    const imports = [
      ...([
        'useBoxAuth',
        'useBoxCcgAuth',
        'useBoxOAuth',
        'useBoxJwtAuth',
        'useBoxAuthConfig'
      ].map(name => ({ from: resolve('./runtime/server/utils/auth'), name }))),
      { from: resolve('./runtime/server/utils/storage'), name: 'useBoxTokenStorage' },
      ...([
        'useBoxClient',
        'useBoxCcgClient',
        'useBoxJwtClient',
        'useBoxOAuthClient'
      ].map(name => ({ from: resolve('./runtime/server/utils/client'), name })))
    ];

    if (options.managers?.composables !== false) {
      managerImports.forEach((name) => {
        imports.push({ from: '#nuxt/box-sdk/managers', name });
      });
    }

    addServerImports(imports);
  }
}

function getInstanceMethods() {
  return (Object.getOwnPropertyNames(BoxClient.prototype) as Array<keyof BoxClient>)
    .filter(m => typeof BoxClient.prototype[m] === 'function' && !/^constructor$/.test(m))
    .reduce((code, m) => {
      // Strip CJS namespace qualifiers (e.g. fetchOptions_1.FetchOptions → FetchOptions).
      // ESM output already uses plain names so this is a no-op there.
      const methodStr = `${BoxClient.prototype[m]}`.replace(/\b\w+_(?:generated_)?\d+\./g, '');
      return `${code}    ${methodStr}\n`;
    }, '');
}

async function createClientDts(managers: string[], _managersAvailable: string[]) {
  const filename = join(await resolvePath('box-node-sdk'), '../../lib/client.d.ts');

  const dts = new MagicString(await promises.readFile(filename, 'utf8'));

  for (const managerAvailable of _managersAvailable) {
    if (!managers.includes(managerAvailable)) {
      dts.replace(
        new RegExp(`import { ${pascalCase(`${managerAvailable}Manager`)} } from './managers/${managerAvailable}.js';\n`),
        ''
      );
      dts.replace(
        new RegExp(`readonly ${managerAvailable}: ${pascalCase(`${managerAvailable}Manager`)};\n`),
        ''
      );
    } else {
      dts.replace(
        new RegExp(`import { ${pascalCase(`${managerAvailable}Manager`)} } from './managers/${managerAvailable}.js';`),
        `import { ${pascalCase(`${managerAvailable}Manager`)} } from 'box-node-sdk/managers/${managerAvailable}';`
      );
    }
  }

  dts.trimLines().trim();

  return dts;
}

function createClientClass(options: ModuleOptions, nuxt = useNuxt()) {
  const filter = createFilter(options.managers?.include, options.managers?.exclude, { resolve: false });
  const _managersAvailable = Object.getOwnPropertyNames(new BoxClient({} as any))
    .filter(n => !['auth', 'networkSession'].includes(n));
  const managers = _managersAvailable.filter(filter);

  const _imports = [
    '// Auto-Generated by \'nuxt-box-sdk\'',
    'import { BaseUrls } from \'box-node-sdk/networking\';',
    'import { NetworkSession } from \'box-node-sdk/networking\';',
    'import { FetchOptions } from \'box-node-sdk/networking\';'
  ];

  const _composablesImports: string[] = [];
  const _composablesDtsImports = [
    'import type { Authentication } from \'box-node-sdk/networking\';',
    'import type { BoxManager, ExtendedManager, BoxManagerNetworkSession } from \'#nuxt/box-sdk/types\';'
  ];

  const _composables: string[] = [];
  const _autoImports: string[] = [];
  const _composablesDts: string[] = [];

  const s = new MagicString(`
export class BoxClient {
    constructor(fields) {
      this.networkSession = fields.networkSession ?? new NetworkSession({
        baseUrls: new BaseUrls({}),
      });
      if (fields.auth) {
        this.auth = fields.auth;
      }`);

  for (const manager of managers) {
    const managerImport = `import { ${pascalCase(`${manager}Manager`)} } from 'box-node-sdk/managers/${manager}';`;
    _imports.push(managerImport);
    _composablesImports.push(managerImport);
    _composablesDtsImports.push(managerImport);
    s.append(`\n    this.${manager} = new ${pascalCase(`${manager}Manager`)}({\n      auth: this.auth,\n      networkSession: this.networkSession,\n    });\n`);

    _composables.push(`export const useBox${pascalCase(`${manager}Manager`)} = /*#__NO_SIDE_EFFECTS__*/ (auth, networkSession) => createBoxManager(${pascalCase(`${manager}Manager`)}, auth, networkSession);`);
    _composablesDts.push(`export declare const useBox${pascalCase(`${manager}Manager`)}: (auth?: Authentication, networkSession?: BoxManagerNetworkSession) => BoxManagerWithAsyncData<typeof ${pascalCase(`${manager}Manager`)}>;`);

    _autoImports.push(`useBox${pascalCase(`${manager}Manager`)}`);
  }

  s.append('    }\n')
    .append(getInstanceMethods())
    .append('}\n');

  s.prepend(_imports.join('\n'));

  const { dst } = addTemplate({
    filename: 'modules/nuxt-box-sdk/client.mjs',
    getContents: () => s.toString()
  });

  addServerTemplate({
    filename: '#nuxt/box-sdk/client',
    getContents: () => s.toString()
  });

  addTypeTemplate({
    filename: 'modules/nuxt-box-sdk/client.d.ts',
    getContents: async () => {
      const dts = await createClientDts(managers, _managersAvailable);

      return dts.prepend('// Auto-Generated by \'nuxt-box-sdk\'\n').toString().split('\n').map((line) => {
        const exc = /import \{ (\w+) \} from '(.*)';/.exec(line); // @ts-ignore
        if (exc?.length && exc[2].startsWith('./')) { // @ts-ignore
          line = line.replace(exc[2], `box-node-sdk/${exc[2].substring(2).replace(/\.js$/, '')}`);
        }
        if (line.search(/\S|$/) > 4) {
          line = line.substring(line.search(/\S|$/) - 4);
        }

        const replaces: Array<[RegExp, string]> = [
          [/constructor\(fields: .*$/, 'constructor(fields: BoxClientInput<T>);'],
          [/export declare class BoxClient/, 'export declare class BoxClient<T extends Authentication = Authentication>'],
          [/export interface BoxClientInput/, 'export interface BoxClientInput<T extends Authentication = Authentication>'],
          [/readonly auth: Authentication/, 'readonly auth: T'],
          [/\): BoxClient;/, '): BoxClient<T>']
        ];

        for (const [regex, replace] of replaces) {
          if (regex.test(line)) {
            line = line.replace(regex, replace);
            break;
          }
        }

        return line;
      }).join('\n');
    }
  });

  nuxt.options.alias['#nuxt/box-sdk/client'] = dst.replace(/\.mjs$/i, '');

  if (options.managers?.composables) {
    const { dst: managersDst } = addTemplate({
      filename: 'modules/nuxt-box-sdk/managers.mjs',
      getContents: () => `${[
        '// Auto-Generated by \'nuxt-box-sdk\'',
        'import { hash } from \'ohash\';',
        'import { createError } from "#imports";',
        'import { computed, toValue } from \'vue\';',
        'import { isFunction, tap } from "@whoj/utils-core";',
        'import { createBoxManager as managerFactory } from \'#nuxt/box-sdk/utils\';',
        'import { FetchOptions } from "box-node-sdk/networking";',
        ..._composablesImports
      ].join('\n')}\n\n${_composables.join('\n')}\nfunction createBoxManager (...args) {
  const [manager, auth, networkSession] = args;
  const Manager = class extends manager {
    withAsyncData(opts = {}) {
      return new Proxy(this, {
        get(target, prop) {
          if (target[prop] && isFunction(target[prop]) && !/with(?:AsUserHeader|SuppressedNotifications|ExtraHeaders|CustomBaseUrls|Proxy|CustomAgentOptions|Interceptors)/.test(prop)) {
            return (...args2) => {
              const _key = computed(() => {
                return \`box:\${manager.name}:\${hash([prop, ...args2.map((a) => toValue(a))])}\`;
              });
              let controller;
              return useAsyncData(
                _key.value,
                async (nuxt) => {
                  controller?.abort?.();
                  if (nuxt && nuxt.isHydrating && nuxt.payload.data[_key.value]) {
                    return nuxt.payload.data[_key.value];
                  }
                  controller = new AbortController();
                  const _target = target.withInterceptors([
                    {
                      beforeRequest(options) {
                        return { ...options, cancellationToken: controller.signal };
                      },
                      afterRequest: (response) => response
                    }
                  ]);
                  try {
                    let result = await _target[prop].call(_target, ...args2.map((a) => toValue(a)));
                    result = JSON.parse(JSON.stringify(result));
                    if (nuxt) {
                      nuxt.payload.data[_key.value] = result;
                    }
                    return tap(JSON.parse(JSON.stringify(result)), (_result) => {
                      return _result;
                    });
                  } catch (error) {
                    if (nuxt) {
                      nuxt.payload.data[_key.value] = void 0;
                    }
                    throw createError(error);
                  }
                },
                {
                  ...opts,
                  watch: [
                    ...opts?.watch || [],
                    () => toValue(args2)
                  ]
                }
              );
            };
          }
          return Reflect.get(target, prop);
        }
      });
    }
  };
  return managerFactory(Manager, auth, networkSession);
};`
    });

    addServerTemplate({
      filename: '#nuxt/box-sdk/managers',
      getContents: () => `${[
        '// Auto-Generated by \'nuxt-box-sdk\'',
        'import { createBoxManager } from \'#nuxt/box-sdk/utils\';',
        ..._composablesImports
      ].join('\n')}\n\n${_composables.join('\n')}`
    });

    addTypeTemplate({
      filename: 'modules/nuxt-box-sdk/managers.d.ts',
      getContents: () => `${[
        '// Auto-Generated by \'nuxt-box-sdk\'',
        'import type { MaybeRefOrGetter } from \'vue\';',
        'import type { Class, PascalCase } from \'@whoj/utils-types\';',
        'import type { DefaultAsyncDataValue } from \'#app/defaults\';',
        'import type { KeysOf, PickFrom } from \'#app/composables/asyncData\';',
        'import { createBoxManager as managerFactory } from \'#nuxt/box-sdk/utils\';',
        'import type { AsyncData, AsyncDataOptions, NuxtApp, NuxtError } from \'#app\';',
        ..._composablesDtsImports
      ].join('\n')}\n\n${_composablesDts.join('\n')}\n\n
type KeysToExclude = 'auth' | 'networkSession' | 'withAsUserHeader' | 'withSuppressedNotifications' | 'withExtraHeaders' | 'withCustomBaseUrls' | 'withProxy' | 'withCustomAgentOptions' | 'withInterceptors';
type MaybeRefOrGetterArgs<T extends unknown[]> = T extends infer LNT ? {
    [L in keyof LNT]: MaybeRefOrGetter<T[L]>;
} : never;
type WithAsyncData<T extends Class<any>> = Class<Pick<T['prototype'], Extract<keyof T['prototype'], KeysToExclude>> & {
    [P in Exclude<keyof T['prototype'], KeysToExclude>]:
      T['prototype'][P] extends ((...args: infer A) => Promise<infer R>)
        ? ((...args: MaybeRefOrGetterArgs<A>) => AsyncData<R, NuxtError>)
        : T['prototype'][P];
}>;
type UseManagerMethodData<T extends Class<any>> = \{
  [P in Exclude<keyof T['prototype'], KeysToExclude> as P extends string ? \`use\${PascalCase<P>}AsyncData\` : never]:
    T['prototype'][P] extends ((...args: infer A) => Promise<infer R>)
      ? ((opts: AsyncDataOptions<R>, ...args: MaybeRefOrGetterArgs<A>) => AsyncData<R, NuxtError>)
      : T['prototype'][P];
};
export interface ExtendedBoxManagerWithAsyncData<T extends Class<any>> extends ExtendedManager {
  withAsyncData(opts?: AsyncDataOptions<any>): InstanceType<WithAsyncData<T>>;

  useAsyncData<ResT, DataT = ResT, PickKeys extends KeysOf<DataT> = KeysOf<DataT>, DefaultT = DataT>(handler: (manager: BoxManager<T>, nuxtApp?: NuxtApp) => Promise<ResT>, options?: AsyncDataOptions<ResT, DataT, PickKeys, DefaultT>): AsyncData<PickFrom<DataT, PickKeys> | DefaultT, NuxtError>;
  useAsyncData<ResT, DataT = ResT, PickKeys extends KeysOf<DataT> = KeysOf<DataT>, DefaultT = DataT>(key: string, handler: (manager: BoxManager<T>, nuxtApp?: NuxtApp) => Promise<ResT>, options?: AsyncDataOptions<ResT, DataT, PickKeys, DefaultT>): AsyncData<PickFrom<DataT, PickKeys> | DefaultT, NuxtError>;

  useLazyAsyncData<ResT, DataT = ResT, PickKeys extends KeysOf<DataT> = KeysOf<DataT>, DefaultT = DataT>(handler: (manager: BoxManager<T>, nuxtApp?: NuxtApp) => Promise<ResT>, options?: Omit<AsyncDataOptions<ResT, DataT, PickKeys, DefaultT>, 'lazy'>): AsyncData<PickFrom<DataT, PickKeys> | DefaultT, NuxtError>;
  useLazyAsyncData<ResT, DataT = ResT, PickKeys extends KeysOf<DataT> = KeysOf<DataT>, DefaultT = DataT>(key: string, handler: (manager: BoxManager<T>, nuxtApp?: NuxtApp) => Promise<ResT>, options?: Omit<AsyncDataOptions<ResT, DataT, PickKeys, DefaultT>, 'lazy'>): AsyncData<PickFrom<DataT, PickKeys> | DefaultT, NuxtError>;
}

export type BoxManagerWithAsyncData<T extends Class<any>> = InstanceType<T> & ExtendedBoxManagerWithAsyncData<T> & UseManagerMethodData<T>;

`
    });
    nuxt.options.alias['#nuxt/box-sdk/managers'] = managersDst.replace(/\.mjs$/i, '');
  }

  return _autoImports;
}
